name: Build Docker image and deploy to Heroku

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ebf83021-a5dd-43ed-b44a-9a4de00c22f4
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ebf83021-a5dd-43ed-b44a-9a4de00c22f4
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web
      - name: Release
        env:
          HEROKU_API_KEY: ebf83021-a5dd-43ed-b44a-9a4de00c22f4
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
